### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by zQueal** [philsturgeon/phptherightway-book#1]
Error Thrown:

```
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'DirectoryIterator::__construct(./web/_posts): failed to open dir: No such file or directory' in /tmp/phptherightway-book-2.0.0/convert.php:6
Stack trace:
#0 /tmp/phptherightway-book-2.0.0/convert.php(6): DirectoryIterator->__construct('./web/_posts')
#1 {main}
  thrown in /tmp/phptherightway-book-2.0.0/convert.php on line 6
```

PHP Version:

```
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

Any ideas?

**Comment by philsturgeon** [comment]
Did you forget to use the --recursive switch when cloning?

---Sent from Boxer | http://getboxer.com

On 6 January 2015 02:41:47 GMT-5, Zach Queal notifications@github.com wrote:Error Thrown:  PHP Fatal error: Uncaught exception 'UnexpectedValueException' with message 'DirectoryIterator::__construct(./web/_posts): failed to open dir: No such file or directory' in /tmp/phptherightway-book-2.0.0/convert.php:6 Stack trace: #0 /tmp/phptherightway-book-2.0.0/convert.php(6): DirectoryIterator->__construct('./web/_posts') #1 {main} thrown in /tmp/phptherightway-book-2.0.0/convert.php on line 6    PHP Version:  PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10) Copyright (c) 1997-2014 The PHP Group Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies    Any ideas?  —Reply to this email directly or view it on GitHub.

**Comment by philsturgeon** [comment]
I'm gonna shut this down. :)
